version: "3.9"

services:
  well-log-api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: well-log-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
